<Project>
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Version>0.1.0</Version>
    <Authors>v-hiker;SimpleScraper contributors</Authors>
    <Copyright>Copyright © 2026 v-hiker and SimpleScraper contributors</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Deterministic>true</Deterministic>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
